name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Directories
        run: |
          mkdir zig
          echo "$(pwd)/zig" >> $GITHUB_PATH

      - name: Download Zig
        working-directory: zig
        run: |
          wget -qO releases.json https://ziglang.org/download/index.json
          wget -qO zig.tar.xf "$(cat releases.json | jq -r '.master."x86_64-linux".tarball')"
          tar --strip-components=1 -xJf zig.tar.xf

      - name: Run tests
        run: zig build test

      - name: Build zangle
        run: zig build -Drelease

      - name: Upload build artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: zangle
          path: zig-out/bin/zangle

